config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts do
    collection do
      get :list
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :content, presence: true, length:{minimum:1, maximum:140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:update, :destroy, :edit, :show]

  def index
  end

  def list
    @posts = Post.all
  end

  def new
    @post =  Post.new
  end

  def create
    @post = Post.new(post_params)
    if params[:Retour]
      render :new
     else
       if @post.save
         flash[:notice] = " Tweet posté avec succès" 
         redirect_to posts_path
       else
         render new_post_path
       end
     end
  end

  def show
  end

  def destroy
    flash[:danger] = " Tweet supprime" 
    redirect_to posts_path if @post.destroy
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:notice] = " Tweet modifié avec succès" 
      redirect_to post_path
    else
      render :edit 
    end
  end

  def confirm
    @post = Post.new(post_params)
    render :new if @post.invalid?
  end
  
  private
  def post_params
    params.require(:post).permit(:content)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    def choose_new_or_edit
        if action_name == 'new' || action_name == 'create'
            url = confirm_posts_path
        elsif action_name == 'edit'
            url = post_path
        end
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TweeterClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true , url: choose_new_or_edit) do |form| %>
    <% content_for :head do %>
    <link rel="stylesheet" href="new.scss">
    <% end %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2> il y a <%= @post.errors.count %> erreurs</h2>
      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="post-tweet">
        <tr >
            <td><%= form.label :"Poster un tweet" %></td>
            <td><%= form.text_field :content %> </td>
        </tr>
           <div class="buttons post-tweet">
                <button> <%= form.submit  "Poster" %> </button>
                <button> <%= link_to "Retour" , posts_path %> </button>
                <% end %>
            </div>  
    </div>
  <br>

app/views/posts/confirm.html.erb
<h1>Confirmation du contenu du tweet</h1>
<div class="content-tweet"> 
    <p> Contenu: <%= @post.content %> </p>       
</div>

<%= form_with(model: @post, local: true , url: posts_path) do |form| %>
    <%= form.hidden_field :content %>  
  <br>
    <div class="buttons">
        <%= form.submit  "Enregistrer" %>
        <%= form.submit  "Retour" , name: 'Retour' %>
    </div>
<% end %>

app/views/posts/edit.html.erb
  <h1> Editer un tweet</h1>
  <%= render 'form' %>

app/views/posts/index.html.erb
<% content_for :head do %>
  <title>Tweeter- Clone</title>
  <link rel="stylesheet" href="index.scss">
<% end %>

<body>
    <header>
        <ul>
            <%= image_tag "logo_twitter.svg" , class:"left", alt:"Twitter-clone icons" %>
            <li class="left"><a href="#"><strong> Twitter<em>Clone</em></strong></a></li>
        </ul>
        <ul >
            <li class="right"> <%= link_to "Bookmarks" %> </li>
            <li class="right"> <%= link_to "Home" %> </li>
            <li class="right"> <%= link_to "Profile" %></li>
        </ul>
    </header>
    <main>
        <section class="main">
            <div class="container">
                <div class="intro">
                    <h2>Home -- <em>What's happening?</em></h2>
                    <p>Nunc luctus in metus eget fringilla. Aliquam sed justo ligula. Vestibulum nibh erat, pellentesque ut laoreet vitae. </p>
                </div>
                <div class="buttons">
                    <button> <%= link_to "Liste des tweets" , list_posts_path %> </button>
                    <button> <%= link_to "Poster un tweet" , new_post_path %> </button>
                </div>
            </div>
        </section>
          <% flash.each do |key, value| %>
    <%= content_tag(:div,value,class:key) %>
    <br>
<% end %>
    </main>
    <footer>
      <p> Copyright  ©</p>
    </footer>
</body>

</html>

app/views/posts/list.html.erb
<% content_for :head do %>
  <title>List |Tweeter- Clone</title>
  <link rel="stylesheet" href="list.scss">
<% end %>
<h1>List des tweets</h1>
<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>
 
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.content %></td>
        <td><%= link_to "Show" , post_path(post.id) %></td>
        <td><%= link_to "Edit" , edit_post_path(post.id) %></td>
        <td><%= link_to "Destroy" , post ,method: "delete", data: {confirm: "Etes vous sur de vouloir supprimer?"} %> </td>
      </tr>
    <% end %>
  </tbody>
</table>
 
<br>

app/views/posts/new.html.erb
  <h1> Poster un tweet</h1>
  <%= render 'form' %>

app/views/posts/show.html.erb
<h1>Visualiser le contenu du tweet</h1>
<div class="content-tweet"> 
    <p> Contenu: <%= @post.content %> </p>       
    <%= link_to "Back", posts_path %>
    <%= link_to "Edit", edit_post_path %>
    <% flash.each do |key, value| %>
    <%= content_tag(:div,value,class:key) %>
    <br>
    <% end %>
</div>